// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExecution() {
  return window['go']['main']['App']['CancelExecution']();
}

export function DockerAction(arg1, arg2) {
  return window['go']['main']['App']['DockerAction'](arg1, arg2);
}

export function DockerLogs(arg1) {
  return window['go']['main']['App']['DockerLogs'](arg1);
}

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function ExportData(arg1) {
  return window['go']['main']['App']['ExportData'](arg1);
}

export function FetchURL(arg1) {
  return window['go']['main']['App']['FetchURL'](arg1);
}

export function GetAllNotes() {
  return window['go']['main']['App']['GetAllNotes']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetChineseSearchMap() {
  return window['go']['main']['App']['GetChineseSearchMap']();
}

export function GetCurrentDistro() {
  return window['go']['main']['App']['GetCurrentDistro']();
}

export function GetDistroInfo() {
  return window['go']['main']['App']['GetDistroInfo']();
}

export function GetDockerContainers() {
  return window['go']['main']['App']['GetDockerContainers']();
}

export function GetGuides() {
  return window['go']['main']['App']['GetGuides']();
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetSysStats() {
  return window['go']['main']['App']['GetSysStats']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function ImportNotes(arg1) {
  return window['go']['main']['App']['ImportNotes'](arg1);
}

export function SaveNote(arg1, arg2) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2);
}

export function TestSSH(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestSSH'](arg1, arg2, arg3, arg4);
}
