// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelExecution():Promise<boolean>;

export function DockerAction(arg1:string,arg2:string):Promise<main.ExecResult>;

export function DockerLogs(arg1:string):Promise<string>;

export function ExecuteCommand(arg1:string):Promise<main.ExecResult>;

export function ExportData(arg1:string):Promise<string>;

export function FetchURL(arg1:string):Promise<main.FetchResult>;

export function GetAllNotes():Promise<string>;

export function GetBeginnerPath():Promise<string>;

export function GetCategories():Promise<Array<main.Category>>;

export function GetChineseSearchMap():Promise<string>;

export function GetCurrentDistro():Promise<string>;

export function GetDistroInfo():Promise<main.DistroInfo>;

export function GetDockerContainers():Promise<string>;

export function GetGuidedSteps(arg1:string):Promise<string>;

export function GetGuides():Promise<Array<main.GuideCategory>>;

export function GetNote(arg1:string):Promise<string>;

export function GetSysStats():Promise<main.SysStats>;

export function GetSystemInfo():Promise<main.SysInfo>;

export function ImportNotes(arg1:string):Promise<boolean>;

export function SaveNote(arg1:string,arg2:string):Promise<boolean>;

export function TestSSH(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ExecResult>;
